apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: queue-corporation
spec:
  scaleTargetRef:
    name: queue-corporation
  minReplicaCount: 0
  maxReplicaCount: 10
  triggers:
  - type: rabbitmq
    metadata:
      host: amqp://rabbitmq.evekill.svc.cluster.local:5672
      protocol: auto
      mode: QueueLength
      queueName: corporation
      value: "10.10"
      vhostName: /
