apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: eve-kill
spec:
  selector:
    app: frontend
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
