apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cache
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-path
  resources:
    requests:
      storage: 50Gi
