apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: queue-character
spec:
  scaleTargetRef:
    name: queue-character
  minReplicaCount: 0
  maxReplicaCount: 10
  triggers:
  - type: rabbitmq
    metadata:
      host: amqp://rabbitmq.evekill.svc.cluster.local:5672/
      protocol: auto
      mode: QueueLength
      queueName: character
