apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: longhorn
