apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: queue-meilisearch
spec:
  scaleTargetRef:
    name: queue-meilisearch
  minReplicaCount: 0
  maxReplicaCount: 1
  triggers:
  - type: rabbitmq
    metadata:
      host: http://keda:keda@rabbitmq.rabbitmq.svc.cluster.local:15672/
      mode: QueueLength
      protocol: auto
      value: "1"
      queueName: meilisearch
