apiVersion: apps/v1
kind: Deployment
metadata:
  name: imageserver
  namespace: eve-kill
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: imageserver
  template:
    metadata:
      labels:
        app: imageserver
    spec:
      restartPolicy: Always
      containers:
        - name: imageserver
          image: ghcr.io/eve-kill/imageserver:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /_healthcheck
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /_healthcheck
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: imageserver
              mountPath: /app/cache
      volumes:
        - name: imageserver
          persistentVolumeClaim:
            claimName: imageserver
