apiVersion: v1
kind: Service
metadata:
  name: imageserver
  namespace: eve-kill
spec:
  selector:
    app: imageserver
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
