apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: imageserver
  namespace: eve-kill
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nvme
  resources:
    requests:
      storage: 50Gi
