apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  selector:
    app: server
  ports:
    - name: http
      protocol: TCP
      port: 9201
      targetPort: 9201
    - name: status
      protocol: TCP
      port: 9202
      targetPort: 9202
