apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: queue-killmail
spec:
  scaleTargetRef:
    name: queue-killmail
  minReplicaCount: 1
  maxReplicaCount: 5
  triggers:
  - type: rabbitmq
    metadata:
      host: http://keda:keda@rabbitmq.rabbitmq.svc.cluster.local:15672/
      mode: QueueLength
      protocol: auto
      value: "1"
      queueName: killmail
