apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: queue-killmail
spec:
  scaleTargetRef:
    name: queue-killmail
  pollingInterval: 5
  cooldownPeriod: 30
  minReplicaCount: 1
  maxReplicaCount: 50
  triggers:
    - type: redis
      metadata:
        address: redis.evekill.svc.cluster.local:6379
        listName: killmail
        listLength: "1"
        activationListLength: "1"
