# Redis config stored as a configmap
apiVersion: v1
kind: ConfigMap
metadata:
  name: evekill-config
data:
  config.php: |-
    <?php

    return [
      'development' => false,
      'logLevel' => 0,
      'ws_token' => '{{ .Values.config.ws_token }}',
      'ollama' => [
        'url' => 'http://ollama.evekill.svc.cluster.local:11434/api/',
        'token' => '{{ .Values.ollama.token }}',
        'model' => 'llama3.1'
      ],
      'mongodb' => [
        'hosts' => [
          'mongodb.mongodb.svc.cluster.local:27017',
        ]
      ],
      'redis' => [
        'host' =>'redis.redis.svc.cluster.local',
        'port' => 6379,
        'password' => '',
        'database' => 0,
      ],
      'meilisearch' => [
        'host' => 'meilisearch.meilisearch.svc.cluster.local:7700'
      ],
      'rabbitmq' => [
        'host' => 'rabbitmq.rabbitmq.svc.cluster.local',
        'port' => 5672,
        'user' => 'evekill',
        'password' => '{{ .Values.rabbitmq.queuePassword }}',
      ],
      'sso' => [
        'prod' => [
          'client_id' => '{{ .Values.config.sso.prod.client_id }}',
          'client_secret' => '{{ .Values.config.sso.prod.client_secret }}',
          'callback_url' => '{{ .Values.config.sso.prod.callback_url }}'
        ]
      ],
      'webhooks' => [
        'comments' => '{{ .Values.config.webhooks.comments }}',
        'esi-errors' => '{{ .Values.config.webhooks.esi_errors }}',
        'errors' => '{{ .Values.config.webhooks.errors }}',
        'new-characters-found' => '{{ .Values.config.webhooks.new_characters_found }}',
      ],
      'openai' => [
        'comments' => '{{ .Values.config.openai.comments}}'
      ]
    ];
