apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: queue-evewho
spec:
  scaleTargetRef:
    name: queue-evewho
  minReplicaCount: 0
  maxReplicaCount: 2
  triggers:
  - type: rabbitmq
    metadata:
      host: amqp://rabbitmq.evekill.svc.cluster.local:5672
      protocol: auto
      mode: QueueLength
      queueName: evewho
      value: "1"
      vhostName: /
