apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
    - name: rabbitmq
      port: 15672
      protocol: TCP
      targetPort: 15672
    - name: stomp
      port: 61613
      protocol: TCP
      targetPort: 61613
