apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobile
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: mobile
  template:
    metadata:
      labels:
        app: mobile
    spec:
      serviceAccountName: evekill
      restartPolicy: Always
      containers:
        - name: mobile
          image: {{ .Values.mobile.image }}:{{ .Values.mobile.version }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: 3000
          env:
            - name: SENTRY_DSN
              value: {{ .Values.sentryDSNmobile }}
            - name: PUBLIC_SENTRY_DSN
              value: {{ .Values.sentryDSNmobile }}
