# Redis config stored as a configmap
apiVersion: v1
kind: ConfigMap
metadata:
  name: relay-config
data:
  credentials.json: |-
    {
      "secret_key": "{{ .Values.sentryRelay.secretKey }}",
      "public_key": "{{ .Values.sentryRelay.publicKey }}",
      "id": "{{ .Values.sentryRelay.id }}"
    }
  config.yml: |-
    logging:
      level: INFO
    relay:
      upstream: {{ .Values.sentryRelay.upstream }}
      host: 0.0.0.0
      port: 3000
