apiVersion: apps/v1
kind: Deployment
metadata:
  name: relay
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: relay
  template:
    metadata:
      labels:
        app: relay
    spec:
      restartPolicy: Always
      containers:
        - name: relay
          image: getsentry/relay:latest
          imagePullPolicy: Always
          command:
            - /usr/bin/relay
            - run
          ports:
            - containerPort: 3000
          env:
            - name: RELAY_PORT
              value: "3000"
          volumeMounts:
            - name: relay-config
              mountPath: /work/.relay/credentials.json
              subPath: credentials.json
            - name: relay-config
              mountPath: /work/.relay/config.yml
              subPath: config.yml
      volumes:
        - name: relay-config
          configMap:
            name: relay-config

