apiVersion: apps/v1
kind: Deployment
metadata:
  name: cron
  namespace: eve-kill
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: cron
  template:
    metadata:
      labels:
        app: cron
    spec:
      restartPolicy: Always
      containers:
        - name: redisq
          image: ghcr.io/eve-kill/backend:latest
          imagePullPolicy: Always
          command:
            - /bin/sh
            - -c
            - |
              ./bin/cron
          volumeMounts:
            - name: eve-kill-config
              mountPath: /app/.env
              subPath: .env
      volumes:
        - name: eve-kill-config
          configMap:
            name: eve-kill-config
