apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: queue-websocket
spec:
  scaleTargetRef:
    name: queue-websocket
  minReplicaCount: 1
  maxReplicaCount: 5
  triggers:
  - type: rabbitmq
    metadata:
      host: amqp://rabbitmq.evekill.svc.cluster.local:5672
      protocol: auto
      mode: QueueLength
      queueName: websocket
      value: "1"
      vhostName: /
