apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: queue-default
spec:
  scaleTargetRef:
    name: queue-default
  minReplicaCount: 0
  maxReplicaCount: 5
  triggers:
  - type: rabbitmq
    metadata:
      host: amqp://rabbitmq.evekill.svc.cluster.local:5672
      protocol: auto
      mode: QueueLength
      queueName: default
      value: "10"
      vhostName: /
