apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 50Gi
