apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: queue-high
spec:
  scaleTargetRef:
    name: queue-high
  triggers:
    - type: redis
      metadata:
        address: redis:6379
        listName: high
        listLength: "1"
