apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: queue-high
spec:
  scaleTargetRef:
    name: queue-high
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
  - type: rabbitmq
    metadata:
      host: amqp://rabbitmq.evekill.svc.cluster.local:5672
      protocol: auto
      mode: QueueLength
      queueName: high
      value: "1.1"
      vhostName: /
