apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: queue-low
spec:
  scaleTargetRef:
    name: queue-low
  minReplicaCount: 0
  maxReplicaCount: 5
  triggers:
  - type: rabbitmq
    metadata:
      host: http://keda:keda@rabbitmq.evekill.svc.cluster.local:15672/
      mode: QueueLength
      protocol: auto
      value: "1"
      queueName: low
