apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: queue-low
spec:
  scaleTargetRef:
    name: queue-low
    kind: Deployment
  minReplicaCount: 0
  maxReplicaCount: 5
  triggers:
  - type: rabbitmq
    metadata:
      host: amqp://rabbitmq.evekill.svc.cluster.local:5672/
      protocol: amqp
      mode: QueueLength
      value: "1"
      queueName: low
