name: Frontend - Build and Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
  repository_dispatch:
    types: [update-frontend]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: eve-kill/frontend

jobs:
  update-frontend-submodule:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Log Payload
        run: |
          echo "Received Payload:"
          echo "================="
          echo "Submodule: ${{ github.event.client_payload.submodule }}"
          echo "Environment: ${{ github.event.client_payload.environment }}"
          echo "Commit: ${{ github.event.client_payload.commit }}"

      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
          ref: main

      - name: Identify the submodule to update
        id: submodule
        run: |
          echo "SUBMODULE=${{ github.event.client_payload.submodule }}" >> $GITHUB_ENV
          echo "COMMIT=${{ github.event.client_payload.commit }}" >> $GITHUB_ENV
          echo "TARGET_BRANCH=main" >> $GITHUB_ENV

      - name: Update submodule
        run: |
          # Checkout the target branch
          git checkout ${TARGET_BRANCH}
          # Setup the configuration for the git user
          git config --global user.name "GitHub Actions"
          git config --global user.email "noreply@eve-kill.com"
          # Update the submodule
          git submodule update --remote -- ${SUBMODULE}
          # Enter the submodule
          cd ${SUBMODULE}
          # Checkout submodule to commit hash
          git checkout ${COMMIT}
          cd -
          # Add the submodule changes
          git add ${SUBMODULE}
          # Commit the submodule changes
          git commit -m "Updated ${SUBMODULE} submodule to commit ${COMMIT} on branch ${TARGET_BRANCH}"
          # Push the submodule changes
          git push origin ${TARGET_BRANCH}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-frontend-container:
    runs-on: ubuntu-latest
    needs: update-frontend-submodule
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
          ref: main

      - name: Get submodule commit hash
        id: short_commit
        run: |
          cd frontend
          SUBMODULE_COMMIT_HASH=$(git rev-parse --short HEAD)
          echo "::set-output name=hash::$SUBMODULE_COMMIT_HASH"

      - name: Create .npmrc
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.REPO_ACCESS_TOKEN }}" > frontend/.npmrc
          echo "@eveshipfit:registry=https://npm.pkg.github.com/" >> frontend/.npmrc

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@aa33708b10e362ff993539393ff100fa93ed6a27 # v3.5.0

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.REPO_ACCESS_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5.5.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            latest
            ${{ steps.short_commit.outputs.hash }}

      - name: Copy the docker folder into the build context
        run: cp -r docker/ frontend/.docker

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@5176d81f87c23d6fc96624dfdbcd9f3830bbe445 # v6.5.0
        with:
          file: docker/node.Dockerfile
          context: frontend/
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          #platforms: linux/amd64,linux/arm64
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy-frontend:
    runs-on: ubuntu-latest
    needs: build-frontend-container
    environment: production
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get short commit hash
        id: short_commit
        run: |
          cd frontend
          SUBMODULE_COMMIT_HASH=$(git rev-parse --short HEAD)
          echo "::set-output name=hash::$SUBMODULE_COMMIT_HASH"

      - name: Write kubeconfig
        run: |
          echo "${{ secrets.KUBERNETES_CONFIG }}" > /tmp/config

      - name: Deploy
        run: |
          kubectl --kubeconfig=/tmp/config -n evekill rollout restart deployment/frontend

      - name: Wait for rollout to finish
        run: |
          kubectl --kubeconfig=/tmp/config -n evekill rollout status deployment/frontend

      - name: Remove kubeconfig
        run: rm -f /tmp/config

  purge-cloudflare-cache:
    runs-on: ubuntu-latest
    needs: deploy-frontend
    environment: production
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Purge Cloudflare Cache
        uses: jakejarvis/cloudflare-purge-action@v0.3.0
        env:
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE_ID }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_CACHE_PURGE_TOKEN }}
