name: Helm-Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'helm-chart/**'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: eve-kill/killboard

jobs:
  deploy-killboard:
    runs-on: ubuntu-latest
    environment: production
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Set up kubectl
        run: |
          tailscale configure kubeconfig tailscale-operator

      - name: Helm Deploy
        run: |
          helm --kubeconfig=$HOME/.kube/config upgrade --install evekill helm-chart/ \
            --namespace evekill \
            --set sentryDSNFrontend=${{ secrets.SENTRY_DSN_FRONTEND }} \
            --set sentryDSN=${{ secrets.SENTRY_DSN_LOCAL }} \
            --set sentryRelay.dsn=${{ secrets.SENTRY_DSN_BACKEND }} \
            --set sentryRelay.upstream=${{ secrets.SENTRY_RELAY_UPSTREAM }} \
            --set sentryRelay.secretKey=${{ secrets.SENTRY_RELAY_SECRET_KEY }} \
            --set sentryRelay.publicKey=${{ secrets.SENTRY_RELAY_PUBLIC_KEY }} \
            --set sentryRelay.id=${{ secrets.SENTRY_RELAY_ID }} \
            --set ws_token=${{ secrets.WS_TOKEN }} \
            --set ollama.token=${{ secrets.OLLAMA_TOKEN }} \
            --set rabbitmq.queuePassword=${{ secrets.RABBITMQ_QUEUE_PASSWORD }} \
            --set config.sso.prod.client_id=${{ secrets.SSO_PROD_CLIENT_ID }} \
            --set config.sso.prod.client_secret=${{ secrets.SSO_PROD_CLIENT_SECRET }} \
            --set config.sso.prod.callback_url=${{ secrets.SSO_PROD_CALLBACK_URL }} \
            --set config.webhooks.comments=${{ secrets.WEBHOOKS_COMMENTS }} \
            --set config.webhooks.esi_errors=${{ secrets.WEBHOOKS_ESI_ERRORS }} \
            --set config.webhooks.errors=${{ secrets.WEBHOOKS_ERRORS }} \
            --set config.webhooks.new_characters_found=${{ secrets.WEBHOOKS_NEW_CHARACTERS_FOUND }} \
            --set config.openai.comments=${{ secrets.OPENAI_COMMENT_MODERATION_KEY }}
            -f helm-chart/values.yaml

      - name: Remove kubeconfig
        run: rm -f $HOME/.kube/config
